apiVersion: batch/v1
kind: CronJob
metadata:
  name: __NAMESPACE__-backup
  namespace: __NAMESPACE__
spec:
  schedule: "0 2 * * *" # Run daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: __BACKUP_KEEP_DAYS__
  failedJobsHistoryLimit: __BACKUP_KEEP_DAYS__
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-serviceaccount
          initContainers:
          - name: prepare-backup
            image: busybox
            command:
              - /bin/sh
              - -c
              - |
                echo "DEBUG" && id && umask &&
                echo "CMD" &&
                chmod -Rv 770 /data/backup-dst
            volumeMounts:
            - name: __BACKUP_PVC__
              mountPath: /data/backup-dst
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
          containers:
          - name: backup
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - |
                echo "DEBUG" && id && umask | tee -a $BF.log
                DATE=$(date +'%Y-%m-%d_%H-%M')
                BF=/data/backup-dst/__NAMESPACE__-${DATE}.tar.gz

                echo "SCALE DOWN" | tee -a $BF.log
                sleep 5 && kubectl scale __APP_RESSOURCE__ __DB_RESSOURCE__ --replicas=0 -n __NAMESPACE__ | tee -a $BF.log

                echo "BACKUP VOLUMES" | tee -a $BF.log
                sleep 30 && tar cvfz $BF /data/*-src >$BF.log 2>&1 ; echo RC=$? | tee -a $BF.log
                
                echo "TAIL BACKUP LOGS"
                tail /data/backup-dst/__NAMESPACE__-${DATE}.tar.gz.log
                
                echo "LIST BACKUPS" | tee -a $BF.log
                ls -l /data/backup-dst/ | tee -a $BF.log

                echo "ROTATE BACKUPS" | tee -a $BF.log
                find /data/backup-dst -type f -name '*.tar.gz*' -mtime +__BACKUP_KEEP_DAYS__ -exec rm -v {} + | tee -a $BF.log
                echo "SCALE UP" | tee -a $BF.log
                sleep 5 && kubectl scale __APP_RESSOURCE__ __DB_RESSOURCE__ --replicas=1 -n __NAMESPACE__ | tee -a $BF.log
            volumeMounts:
            - name: __BACKUP_PVC__
              mountPath: /data/backup-dst
            - name: __APP_PVC__
              mountPath: /data/app-src
            - name: __DB_PVC__
              mountPath: /data/db-src
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
          restartPolicy: Never
          volumes:
          - name: __APP_PVC__
            persistentVolumeClaim:
              claimName: __APP_PVC__
          - name: __DB_PVC__
            persistentVolumeClaim:
              claimName: __DB_PVC__
          - name: __BACKUP_PVC__
            persistentVolumeClaim:
              claimName: __BACKUP_PVC__

